// Command genledger regenerates docs/divergence-ledger.md from the backends'
// registered divergence ledgers. Run `go generate ./...` from anywhere in
// the module (the directive lives in provider/divergence.go); the tool
// locates the repo root by walking up to go.mod.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/yi-nology/git-platform-sdk/backends/forgejo"
	"github.com/yi-nology/git-platform-sdk/backends/gitcode"
	"github.com/yi-nology/git-platform-sdk/backends/gitea"
	"github.com/yi-nology/git-platform-sdk/backends/gitee"
	"github.com/yi-nology/git-platform-sdk/backends/github"
	"github.com/yi-nology/git-platform-sdk/backends/gitlab"
	"github.com/yi-nology/git-platform-sdk/backends/tencentcode"
	"github.com/yi-nology/git-platform-sdk/provider"
)

func main() {
	out := filepath.Join(repoRoot(), "docs", "divergence-ledger.md")
	if err := os.WriteFile(out, []byte(render()), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, "genledger: write:", err)
		os.Exit(1)
	}
	fmt.Println("genledger: wrote", out)
}

// render builds the ledger document. It lives in main but is exercised by
// main_test against the committed file so the two cannot drift.
func render() string {
	type backendLedger struct {
		name string
		divs []provider.Divergence
	}
	ledgers := []backendLedger{
		{"gitlab", gitlab.Divergences()},
		{"github", github.Divergences()},
		{"gitee", gitee.Divergences()},
		{"gitea", gitea.Divergences()},
		{"forgejo", forgejo.Divergences()},
		{"gitcode", gitcode.Divergences()},
		{"tencent_code", tencentcode.Divergences()},
	}
	var b strings.Builder
	b.WriteString(header)
	for _, l := range ledgers {
		if len(l.divs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n| Capability | Method | Field | Kind | Reason |\n|---|---|---|---|---|\n", l.name)
		for _, d := range l.divs {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
				d.Capability, d.Method, d.Field, d.Kind, strings.ReplaceAll(d.Reason, "|", "\\|"))
		}
	}
	return b.String()
}

const header = `<!-- Code generated by internal/tools/genledger; DO NOT EDIT. -->
<!-- Regenerate with: go generate ./... (directive lives in provider/divergence.go) -->

# Platform divergence ledger

This document is generated from the backends' registered divergence ledgers
(provider.Divergence). Kinds:

- **stub**: the platform cannot serve the method; the call returns an error
  wrapping provider.ErrNotImplemented and touches no wire.
- **ignore**: the named field (or, when Field is empty, the whole call) is
  silently dropped; the call succeeds without that effect.
- **mapping**: the call returns the closest platform equivalent, an
  approximation of the unified semantics.
- **detour**: the method bypasses the platform SDK and drives the raw
  transport client; behavior is unchanged, the entry is for maintainers.

## Standing limitations

- The gitea and forgejo SDKs accept no context on most calls, so context
  cancellation does not propagate into in-flight requests on those
  platforms.
- Milestone identifiers are platform-specific (a per-repo serial number on
  GitHub and Gitee, a platform ID on GitLab, Gitea, Forgejo, GitCode, and
  Tencent Code); Milestone.Number round-trips only on the platform it came
  from.
`

// repoRoot walks up from the working directory to the module root.
func repoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, "genledger: getwd:", err)
		os.Exit(1)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "genledger: go.mod not found upward from cwd")
			os.Exit(1)
		}
		dir = parent
	}
}
